version: "3"
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PHM_ROOT_PASSWORD=root
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    links:
      - mariadb
  ss:
    image: ss
    environment:
      - PMA_HOST=mariadb
    restart: always
    ports:
      - 3000:80
    volumes:
        - /new /var/www/html
    links:
      - mariadb
