apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ss
  name: ss
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ss
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: ss
    spec:
      containers:
        - env:
            - name: PMA_HOST
              value: mariadb
          image: ss
          name: ss
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /new /var/www/html
              name: ss-claim0
      restartPolicy: Always
      volumes:
        - name: ss-claim0
          persistentVolumeClaim:
            claimName: ss-claim0
status: {}
